###
GET http://localhost:4004/odata/v4/formula-modeler-services/Formulae?$expand=Models

###
POST http://localhost:4004/odata/v4/formula-modeler-services/Formulae
Content-Type: application/json

{
    "title": "Test Formula",
    "description": "Test Formula calculation",
    "formula": "MODEL1.SURCHARGE1 + MODEL1.SURCHARGE2",
    "modelAliases": "[\"MODEL1\"]"
}
###
POST http://localhost:4004/odata/v4/formula-modeler-services/buildFormulaOnModelbyFormulaID
Content-Type: application/json

{
    "formulaID": "5f9a3d2c-1b4e-7c8f-9e6a-2b3f4d1a5c7e",
    "params" : {
        "keys": ["ID","STORE_ID","CUSTOMER_ID","TRANSACTION_DATE"],
        "filters" : []
    }
}

###
GET http://localhost:4004/odata/v4/formula-modeler-services/retrieveDataForFormulaID
Content-Type: application/json

{
    "formulaID": "5f9a3d2c-1b4e-7c8f-9e6a-2b3f4d1a5c7e"
}

###
POST http://localhost:4004/odata/v4/formula-modeler-services/buildFormulaOnModelbyFormulaID
Content-Type: application/json

{
    "formulaID": "b45c2d8e-1f3a-4b6c-8d9e-0f1a2b3c4d5e",
    "params" : {
        "keys": ["product_id"],
        "filters" : []
    }
}

###
GET http://localhost:4004/odata/v4/formula-modeler-services/retrieveDataForFormulaID?$top=100&$skip=200
Content-Type: application/json

{
    "formulaID": "b45c2d8e-1f3a-4b6c-8d9e-0f1a2b3c4d5e"
}