
###
GET http://localhost:4004/odata/v4/formula-modeler-services/Formulae

###
GET http://localhost:4004/odata/v4/formula-modeler-services/Formulae?$expand=Models&$expand=Nodes&$expand=Edges

###
# 0480103b-4867-4994-9fbd-7c14d4020d2d
# Create a TargetModels.view.xml with a table bound to /FormulaModels?$expand=model&$filter=parent_ID eq '{formulaId}' and display the columns targetModel, schemaName, modelAlias from the expanded model.
GET http://localhost:4004/odata/v4/formula-modeler-services/FormulaModels?$expand=model&$filter=parent_ID eq 'b45c2d8e-1f3a-4b6c-8d9e-0f1a2b3c4d5e'



###
POST http://localhost:4004/odata/v4/formula-modeler-services/Formulae
Content-Type: application/json

{
    "title": "Test Formula",
    "description": "Test Formula calculation",
    "formula": "MODEL1.SURCHARGE1 + MODEL1.SURCHARGE2",
    "modelAliases": "[\"MODEL1\"]"
}
###
POST http://localhost:4004/odata/v4/formula-modeler-services/buildFormulaOnModelbyFormulaID
Content-Type: application/json

{
    "formulaID": "5f9a3d2c-1b4e-7c8f-9e6a-2b3f4d1a5c7e",
    "params" : {
        "keys": ["ID","STORE_ID","CUSTOMER_ID","TRANSACTION_DATE"],
        "filters" : []
    }
}

###
GET http://localhost:4004/odata/v4/formula-modeler-services/retrieveDataForFormulaID
Content-Type: application/json

{
    "formulaID": "5f9a3d2c-1b4e-7c8f-9e6a-2b3f4d1a5c7e"
}

###
POST http://localhost:4004/odata/v4/formula-modeler-services/buildFormulaOnModelbyFormulaID
Content-Type: application/json

{
    "formulaID": "b45c2d8e-1f3a-4b6c-8d9e-0f1a2b3c4d5e",
    "params" : {
        "keys": ["product_id"],
        "filters" : []
    }
}

###
GET http://localhost:4004/odata/v4/formula-modeler-services/retrieveDataForFormulaID?$top=100&$skip=200
Content-Type: application/json

{
    "formulaID": "b45c2d8e-1f3a-4b6c-8d9e-0f1a2b3c4d5e"
}

###
POST http://localhost:4004/odata/v4/formula-modeler-services/Formulae
Content-Type: application/json

{
      "title": "Actual Price - 20250521",
      "description": "Actual Price Calculation - corrected",
      "formula": "(\"list_price\"-\"list_price\"*(\"discount_percentage\"/100))",
      "Models": [
        {
          "model_ID": "6a3e9f1b-2d8c-4a7d-9f3e-12c4d5e6f7a8"
        }
      ],
      "Nodes" : [
        {
          "node_formula" : "ACTUAL_PRICE_NEW"
          }
      ]
    }


###
POST http://localhost:4004/odata/v4/formula-modeler-services/Formulae
Content-Type: application/json

{
      "title": "Actual Price 3",
      "description": "Actual Price Calculation 3",
      "formula": "\"discount_percentage\"*100+\"list_price\"*\"volume\"",
      "Models": [
        {
          "model_ID": "6a3e9f1b-2d8c-4a7d-9f3e-12c4d5e6f7a8"
        }
      ],
      "Nodes" : [
        {
          "node_formula" : "Price test calculation"
          }
      ]
    }



###
POST http://localhost:4004/odata/v4/formula-modeler-services/buildFormulaOnModelbyFormulaID
Content-Type: application/json

{
    "formulaID": "95f471b7-8345-4119-91a9-c9d790397552",
    "params" : {
        "keys": ["product_id"],
        "filters" : []
    }
}

###
GET http://localhost:4004/odata/v4/formula-modeler-services/retrieveDataForFormulaID?$top=100&$skip=200
Content-Type: application/json

{
    "formulaID": "95f471b7-8345-4119-91a9-c9d790397552"
}


###
DELETE http://localhost:4004/odata/v4/formula-modeler-services/Formulae('6bec1c24-bf39-40f0-a84a-ec6cecf34e43')


###
POST http://localhost:4004/odata/v4/formula-modeler-services/previewFormulaData
Content-Type: application/json

{
    "formulaID": "2de85b35-37f0-4989-b20d-ff9722a736c4"
}
###


POST http://localhost:4004/odata/v4/formula-modeler-services/buildFormulaOnModelbyFormulaID
Content-Type: application/json

{
    "formulaID": "04db2f8a-bc83-4762-a97e-3375c6aa77df",
    "params" : {
        "keys": ["category"],
        "filters" : []
    }
}

###
POST http://localhost:4004/odata/v4/formula-modeler-services/Formulae
Content-Type: application/json

{
      "title": "f_test_41",
      "description": "Formula 41",
      "formula": "max(price over (product_code,category,item_id))*price",
      "Models": [
        {
          "model_ID": "6a3e9f1b-2d8c-4a7d-9f3e-12c4d5e6f7a8"
        }
      ],
      "Nodes" : [
        {
          "node_formula" : "f_test_41",
          "Parameters": [
               {"parameter_value" : "product_code"},
               {"parameter_value" : "category"},
               {"parameter_value" : "item_id"},
               {"parameter_value" : "product_id"}
              ]
          }
          
      ]
    }
//8c8ecb7c-8e7c-43da-a156-d0d9838cc6f3
###

GET http://localhost:4004/odata/v4/formula-modeler-services/retrieveDataForFormulaID?$top=100&$skip=200
Content-Type: application/json

{
    "formulaID": "6bec1c24-bf39-40f0-a84a-ec6cecf34e43"
}
